services:
  - type: worker
    name: music-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python direct_bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8281137886:AAFBcWfTYmTM39g9OucuAKSiggOxqwS3MCQ